
=begin
QUESTION 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000. 
=end
def multiplesOf(num)
	i, sum = 0, 0
	while i < num
		if i % 3 == 0 or i % 5 == 0
			sum += i
		end
		i += 1
	end
	sum
end


=begin
Question 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
=end
def even_fib(num)
	curr, last = 2, 1
	#temp = 0
	sum = 0
	while curr < num
		sum += curr if curr % 2 == 0

		last, curr = curr, curr+=last
		#temp = curr
		#curr += last
		#last = temp
	end
	sum
end


=begin
Question 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 
=end
def largestPrime(num)
	a = Array.new
	i = 2
	while  num > 1
		while num % i == 0
			a << i
			num /= i
		end
		i += 1
	end
	a.last
end

#####TEST CASES######


puts multiplesOf(10)
puts multiplesOf(1000)
puts ""

puts even_fib(10)
puts even_fib(100)
puts even_fib(1000)
puts even_fib(4000000)
puts ""

puts largestPrime(100)
puts largestPrime(13195)
puts largestPrime(13195)
puts largestPrime(600851475143)







			